### PR TITLE
feat(sass): Replace stylus with sass

### PR DESCRIPTION
**Pull request by fesor**
Sass is currently most popular css preprocessor. It is used by most popular UI toolkits like [Twitter Bootstrap](https://github.com/twbs/bootstrap-sass) or [Angular Material](https://github.com/angular/material).

By switching from stylus to sass we will provide more flexible and ready to use solution.

### CODE REVIEW

**Comment by fesor** [comment]
@gdi2290 @Hendrixer What do you guys think?

**Comment by gdi2290** [comment]
yeah scss is more popular

**Comment by fabianVeliz** [comment]
First thing I did when I downloaded NG6 was replace stylus by sass :)

**Comment by gdi2290** [comment]
thanks

**Pull request merged**
